services:
  mysql: 
    image: mariadb:10.6.25    
    container_name: solareye_mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: solar_eye
        MYSQL_USER: solar
        MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql"

  backend:
    build: "./backend"
    container_name: solareye_backend
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: solar
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: solar_eye
    ports:
      - "3001:3001"
  frontend:
    build: "./frontend"
    container_name: solareye_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
volumes:
  mysql_data: